# Generated by Django 4.2.21 on 2025-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0002_rename_livros_postagemlivros'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemlivros',
            name='autor_postagem',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
