# Generated by Django 4.2.21 on 2025-06-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0003_postagemlivros_autor_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('apelido', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
