# Generated by Django 4.2.21 on 2025-06-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0005_alter_postagemlivros_data_postagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'verbose_name': 'Nome', 'verbose_name_plural': 'Nomes'},
        ),
        migrations.AlterModelOptions(
            name='postagemlivros',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
    ]
