# Generated by Django 4.2.21 on 2025-06-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0006_alter_cadastro_options_alter_postagemlivros_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'verbose_name': 'Usuaio', 'verbose_name_plural': 'Usuaarios'},
        ),
    ]
