# Generated by Django 4.2.21 on 2025-06-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0007_alter_cadastro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemlivros',
            name='autor_postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro', to='blog_livros.cadastro'),
        ),
    ]
