# Generated by Django 4.2.21 on 2025-06-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0008_alter_postagemlivros_autor_postagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
