# Generated by Django 4.2.21 on 2025-06-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_livros', '0009_alter_cadastro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['nome', 'sobrenome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
